Sistr v1.1.3 new Galaxy wrapper release
phac-nml/galaxy_tools pull request #268
Opened 2024-12-17 10:34 UTC by kbessonov1984

This is a new and improved SISTR v1.1.3 Galaxy wrapper that
- provides support for the new `-list-of-serovars` option introduced in this release allowing user to use default or custom list of serovars to check SISTR prediction against
- now all output items in the history get filename added to their name to allow for easier identification especially in cases a `History` has large items
- Updated tests to check for the serovar in the list feature

2024-12-19 18:46 UTC, emarinier requested changes
I ran it locally through planemo on some test data and didn't see any errors. I'm on vacation for two weeks after today, so I won't be able to approve after further changes. Might want to ask @apetkau to give it a final look over later.

2024-12-19 18:46 UTC, emarinier commented on tools/sistr_cmd/sistr_cmd.xml
> +      --list-of-serovars
Yeah, I ran this locally and this was the command it made:

```
sistr -i '/tmp/tmprsd3h0ia/files/9/a/9/dataset_9a925318-cf30-4d65-a67d-ff25dc86c75c.dat' '00_0163' -f tab -o sistr-report.tab -p /tmp/tmprsd3h0ia/job_working_directory/000/2/outputs/dataset_420e7d67-6458-456d-8ba4-ccd6ec121b6f.dat -n /tmp/tmprsd3h0ia/job_working_directory/000/2/outputs/dataset_186fc04f-19dd-4074-8570-d9290967021a.dat -a /tmp/tmprsd3h0ia/job_working_directory/000/2/outputs/dataset_74bab77c-1e5f-488b-8610-65378cc89324.dat --run-mash --qc --list-of-serovars --threads "${GALAXY_SLOTS:-1}" -T "${TMPDIR:-/tmp}" -vv
```

It didn't fail, but it create a hanging `--list-of-serovars`. Is that right?

2024-12-19 18:54 UTC, kbessonov1984 commented on tools/sistr_cmd/sistr_cmd.xml
> +        help="if no file selected, the default one is used available at https://raw.githubusercontent.com/phac-nml/sistr_cmd/177a6dac8148dcb043ab7b344d8c8412aa45c881/sistr/data/serovar-list.txt"
Yes we can use more general URL, but it might change with different SISTR version in future, so I wanted it to be version specific.

2024-12-19 19:10 UTC, kbessonov1984 commented on tools/sistr_cmd/.shed.yml
> +long_description: Salmonella In Silico Typing Resource (SISTR) commandline tool for serovar prediction
This was fixed. Corrected spelling. Thank you

2024-12-19 20:09 UTC, kbessonov1984 commented on tools/sistr_cmd/sistr_cmd.xml
> +        compare="sim_size">
Yes the `diff` is a better way. I found that slightly different results are generated depending on the `sistr` installation environment most probably due to slightly allele difference in sorting giving this randomness. This test is not very critical but shows that some sources of variation do exist. I changed to `diff`

2024-12-19 20:44 UTC, apetkau approved these changes

2024-12-19 20:58 UTC, emarinier commented on tools/sistr_cmd/.shed.yml
> +long_description: Salmonella In Silico Typing Resource (SISTR) commandline tool for serovar prediction
I don't think this was changed.

2024-12-19 21:01 UTC, emarinier commented on tools/sistr_cmd/sistr_cmd.xml
> +        help="if no file selected, the default one is used available at https://raw.githubusercontent.com/phac-nml/sistr_cmd/177a6dac8148dcb043ab7b344d8c8412aa45c881/sistr/data/serovar-list.txt"
What about using the v1.1.3 tag?

https://raw.githubusercontent.com/phac-nml/sistr_cmd/v1.1.3/sistr/data/serovar-list.txt

2024-12-20 00:01 UTC, kbessonov1984 commented on tools/sistr_cmd/sistr_cmd.xml
> +        help="if no file selected, the default one is used available at https://raw.githubusercontent.com/phac-nml/sistr_cmd/177a6dac8148dcb043ab7b344d8c8412aa45c881/sistr/data/serovar-list.txt"
ok, that is the best solution

2024-12-20 04:01 UTC, kbessonov1984 commented on tools/sistr_cmd/.shed.yml
> +long_description: Salmonella In Silico Typing Resource (SISTR) commandline tool for serovar prediction
oh, I changed in the `sistr_cmd.xml` which had identical typo. I now changed in `.shed.yml`

2024-12-20 04:03 UTC, kbessonov1984 commented
completed all requests

2024-12-20 18:26 UTC, apetkau approved these changes
Looks great. Thanks so much.

2024-12-20 18:26 UTC, merged